name: tic_tac_toe
version: 1.0.0+1
publish_to: "none"

description: A cross-platform Tic Tac Toe app in Flutter.

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.0
  http: ^1.2.2
  shared_preferences: ^2.3.2
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
